# 提升 Gradle 可用内存
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA 目前对 configuration cache 支持不完整,见:
# https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric 相关版本,可在 https://fabricmc.net/develop/ 查看最新推荐版本
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# 模组信息
mod_version=1.0.0
maven_group=com.memorysweep

# 依赖
fabric_api_version=0.155.2+26.1.2
